# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Robot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Robot.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0bRobot.proto\"\xad\x01\n\x08Odometry\x12\r\n\x05pos_x\x18\x01 \x01(\x05\x12\r\n\x05pos_y\x18\x02 \x01(\x05\x12\x0f\n\x07heading\x18\x03 \x01(\x05\x12\x12\n\nvel_linear\x18\x04 \x01(\x05\x12\x13\n\x0bvel_angular\x18\x05 \x01(\x05\x12\x16\n\x0e\x64ist_US_Frente\x18\x06 \x01(\r\x12\x17\n\x0f\x64ist_US_Direito\x18\x07 \x01(\r\x12\x18\n\x10\x64ist_US_Esquerdo\x18\x08 \x01(\r\"&\n\x04PIDs\x12\x0e\n\x06velLin\x18\x01 \x01(\x05\x12\x0e\n\x06velAng\x18\x02 \x01(\x05\x62\x06proto3')
)




_ODOMETRY = _descriptor.Descriptor(
  name='Odometry',
  full_name='Odometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='Odometry.pos_x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='Odometry.pos_y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heading', full_name='Odometry.heading', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_linear', full_name='Odometry.vel_linear', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel_angular', full_name='Odometry.vel_angular', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_US_Frente', full_name='Odometry.dist_US_Frente', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_US_Direito', full_name='Odometry.dist_US_Direito', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_US_Esquerdo', full_name='Odometry.dist_US_Esquerdo', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=189,
)


_PIDS = _descriptor.Descriptor(
  name='PIDs',
  full_name='PIDs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='velLin', full_name='PIDs.velLin', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velAng', full_name='PIDs.velAng', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=229,
)

DESCRIPTOR.message_types_by_name['Odometry'] = _ODOMETRY
DESCRIPTOR.message_types_by_name['PIDs'] = _PIDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Odometry = _reflection.GeneratedProtocolMessageType('Odometry', (_message.Message,), dict(
  DESCRIPTOR = _ODOMETRY,
  __module__ = 'Robot_pb2'
  # @@protoc_insertion_point(class_scope:Odometry)
  ))
_sym_db.RegisterMessage(Odometry)

PIDs = _reflection.GeneratedProtocolMessageType('PIDs', (_message.Message,), dict(
  DESCRIPTOR = _PIDS,
  __module__ = 'Robot_pb2'
  # @@protoc_insertion_point(class_scope:PIDs)
  ))
_sym_db.RegisterMessage(PIDs)


# @@protoc_insertion_point(module_scope)
