protoc: Robot.proto
	/home/ronan/PG/nanopb/generator-bin/protoc --nanopb_out=. Robot.proto

cp:
	cp /home/ronan/PG/Codes/Pi\ -\ Arduino\ communication/RPi\ nanopb/exemplo.proto /home/ronan/PG/Codes/Pi\ -\ Arduino\ communication/teste/exemplo.proto

clean:
	rm Robot.pb.c Robot.pb.h
