/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Mon Nov 19 17:39:33 2018. */

#ifndef PB_ROBOT_PB_H_INCLUDED
#define PB_ROBOT_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Odometry {
    int32_t pos_x;
    int32_t pos_y;
    int32_t heading;
    int32_t vel_linear;
    int32_t vel_angular;
    uint32_t dist_US_Frente;
    uint32_t dist_US_Direito;
    uint32_t dist_US_Esquerdo;
/* @@protoc_insertion_point(struct:Odometry) */
} Odometry;

typedef struct _PIDs {
    int32_t velLin;
    int32_t velAng;
/* @@protoc_insertion_point(struct:PIDs) */
} PIDs;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Odometry_init_default                    {0, 0, 0, 0, 0, 0, 0, 0}
#define PIDs_init_default                        {0, 0}
#define Odometry_init_zero                       {0, 0, 0, 0, 0, 0, 0, 0}
#define PIDs_init_zero                           {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Odometry_pos_x_tag                       1
#define Odometry_pos_y_tag                       2
#define Odometry_heading_tag                     3
#define Odometry_vel_linear_tag                  4
#define Odometry_vel_angular_tag                 5
#define Odometry_dist_US_Frente_tag              6
#define Odometry_dist_US_Direito_tag             7
#define Odometry_dist_US_Esquerdo_tag            8
#define PIDs_velLin_tag                          1
#define PIDs_velAng_tag                          2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Odometry_fields[9];
extern const pb_field_t PIDs_fields[3];

/* Maximum encoded size of messages (where known) */
#define Odometry_size                            73
#define PIDs_size                                22

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ROBOT_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
