/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Mon Nov 19 17:39:33 2018. */

#include "Robot.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Odometry_fields[9] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, Odometry, pos_x, pos_x, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, Odometry, pos_y, pos_x, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, Odometry, heading, pos_y, 0),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, Odometry, vel_linear, heading, 0),
    PB_FIELD(  5, INT32   , SINGULAR, STATIC  , OTHER, Odometry, vel_angular, vel_linear, 0),
    PB_FIELD(  6, UINT32  , SINGULAR, STATIC  , OTHER, Odometry, dist_US_Frente, vel_angular, 0),
    PB_FIELD(  7, UINT32  , SINGULAR, STATIC  , OTHER, Odometry, dist_US_Direito, dist_US_Frente, 0),
    PB_FIELD(  8, UINT32  , SINGULAR, STATIC  , OTHER, Odometry, dist_US_Esquerdo, dist_US_Direito, 0),
    PB_LAST_FIELD
};

const pb_field_t PIDs_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, PIDs, velLin, velLin, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, PIDs, velAng, velLin, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
